Add cartpole example for DQN
MathisFederico/LearnRL pull request #65
Opened 2020-08-25 21:53 UTC by Cr4zySheep

Note : Ne fonctionne pas tant que #59 n'est pas merge à cause de la correction `dtype=np.int64`.

2020-08-26 23:15 UTC, MathisFederico commented
> 
> 
> Note : Ne fonctionne pas tant que #59 n'est pas merge à cause de la correction `dtype=np.int64`.

C'est fix mnt ?

2020-08-26 23:19 UTC, MathisFederico requested changes
Très sympa ! Merci encore !
Ce serait encore mieux dans un dossier à part comme ça on mettra aussi le jupyter du tuto, des images/gifs et un README pour expliquer un minimum !

2020-08-26 23:19 UTC, MathisFederico commented on examples/cartpole.py
> +# from learnrl.callbacks.tensorflow import TensorboardCallback
On va pe attendre le merge de l'autre branche avant pour avoir les callbacks !

2020-08-26 23:19 UTC, MathisFederico commented on examples/cartpole.py
> +       # callbacks=[TensorboardCallback(log_dir='./logs_test/', run_name='test_model')]
Pas fan du run_name ici !

2020-08-26 23:19 UTC, MathisFederico commented on examples/cartpole.py
> +                      exploration_decay=0,
Il s'en sort bien avec une exploration fixe ?

2020-08-26 23:19 UTC, MathisFederico commented on examples/cartpole.py
> +pg.run(100,
Utiliser .fit() fait automatiquement render=False et learn=True !

2020-08-26 23:19 UTC, MathisFederico commented on examples/cartpole.py
> +       learn=True,
Ajout d'un reward_scaler suite au tuto ?

2020-08-29 18:02 UTC, Cr4zySheep commented on examples/cartpole.py
> +                      exploration_decay=0,
Ca allait, mais c'était peut-être pas le plus efficace. J'essayerais avec un decay pour voir si ça se stabilise mieux vers la fin.

2020-08-29 18:03 UTC, Cr4zySheep commented on examples/cartpole.py
> +       learn=True,
Ouaip, je ferais ça!

2020-08-29 18:03 UTC, Cr4zySheep commented on examples/cartpole.py
> +       # callbacks=[TensorboardCallback(log_dir='./logs_test/', run_name='test_model')]
Oups, c'est un oubli, je le retirerai ou changerai.

2020-08-29 18:05 UTC, Cr4zySheep commented
> 
> 
> > Note : Ne fonctionne pas tant que #59 n'est pas merge à cause de la correction `dtype=np.int64`.
> 
> C'est fix mnt ?

Oui, maintenant que tu as ajouté le bugfix, c'est fix !

2020-11-17 10:01 UTC, MathisFederico approved these changes
Niquel !
L'histoire de la verbose tu préfère attendre et changer ici ou que je fasse le fix dans ma PR ?

2020-11-17 10:09 UTC, Cr4zySheep commented on examples/cartpole/README.md
> +The `verbose` argument allows to set logging level : 0 (Silent, no logging), 1 (Episode cycles), 2 (Episodes), 3 (Steps), 4 (Detailed steps).
Tu pourras le changer dans ta PR, ça sera plus logique je pense.

2020-11-17 14:38 UTC, merged